---
language: node_js
node_js:
  - "6"

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bower cache

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test

after_success:
  - ci_success.sh
